apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lidarr

helmCharts:
- name: app-template
  releaseName: lidarr-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.0
  valuesFile: values.yaml
  namespace: lidarr
