apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarr

helmCharts:
- name: app-template
  releaseName: sonarr-anime-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.2
  valuesFile: values.yaml
  namespace: sonarr
