apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radarr

helmCharts:
- name: app-template
  releaseName: radarr-instance
  repo: https://bjw-s-labs.github.io/helm-charts
  version: 4.5.0
  valuesFile: values.yaml
  namespace: radarr
